### ISSUE TITLE
Refactor of screens

### ISSUE THREAD

**Issue by thervh70** [thervh70/SEM_Team9#141]
The menu has too many buttons and savegame loading is not really clear.
We must create a new/load gamescreen before we advance to the main menu.
In this screen we give the user the option to pick an existing savegame or to generate a new one with an input field.

This way, when you leave your game, you'll stay in your "account" when you go to the main menu. In that case you can buy new skins still logged in. 

This will also mean that you have to display the current user somewhere in the main menu.

- [ ] New login screen
- [ ] Stay logged in on menu
- [ ] Display user

< feature, user-interface

**Comment by mpsijm** [comment]
Duplicate of #140.
