### ISSUE TITLE
Resolve HighscoreServer feedback

### ISSUE THREAD

**Issue by mpsijm** [thervh70/SEM_Team9#174]
Jurgen's feedback:

174a: naming and documentation
- [x] When launching a new server when the application is already open it says: exiting, but does not. Also throws an exception (in CLIThread) when finally closing it manually before ultimately being shut down.
- [x] Extending Thread is an anti-pattern. It’s better to create (or implement) a Runnable and run that in a new Thread. Nice read: http://stackoverflow.com/questions/541487/implements-
runnable-vs-extends-thread
- [x] Is there a reason to have 5 commands that shutdown the server, without having any different behavior?
- [x] Highscores#add has an if statement that is not needed. The block only passes the Boolean value of the equals. Redundant code.
- [x]  Highscore#parse Javadoc states that it parses any toStrong() method to a Highscore.
- [x] ServerSocket in HighscoreServer shouldn't be called `ss`

174b: parsing and testing
- [x] Nearly all of the classes manipulate Strings in some way to function properly. This is a bad design. It would be better to have some sort of ‘parser’ class that eats all the data that is received and digests them in Objects that your application can understand. Otherwise the scalability is greatly reduced.
- [x] Massive whitespace in console between different connects.
- [x] Testing communication (Unit test instead of Integration test , prevents test hanging)

174c: GUI improvements (to make it all more intuitive)
- [x] Sending highscores only works from the HighScores menu.
- [x] Highscores are overwritten, but cannot view my own top 10 highscores.
- [x] E2E should test HighscoreScene.

**Comment by thervh70** [comment]
B and C are moved to the final iteration, because of lack of time.
