### ISSUE TITLE
Generating more track

### ISSUE THREAD

**Issue by MKerkhof** [thervh70/SEM_Team9#23]
The track has to be infinitely long, after starting, there has to be generated more track as the player moves along it.

**Comment by mpsijm** [comment]
This already exists, but the track also has to be broken down behind the player. Currently there is no need for this yet, because there is only one lane and the player usually dies in the first minute.

**Comment by MathiasMeuleman** [comment]
- [ ] Remove entities from list when off screen
- [ ] Create proper generating algorithms
  - [ ] Generate nice lanes of coins
  - [ ] Generate obstacles over multiple lanes
