### ISSUE TITLE
Displaying the distance

### ISSUE THREAD

**Issue by MKerkhof** [thervh70/SEM_Team9#31]
A ingame meter that shows the distance ran in units

**Comment by mdingjan** [comment]
The ingame meter works and updates the distance every 50 moves of the track in the window. The extra methods I added to the Track class have been tested and succeed. In order to increase coverage even more I will add some last tests. After these last tests, this branch is ready for review.

**Comment by mdingjan** [comment]
The distance is being monitored and is displayed on the screen every 50 moves.
Therefore this branch is ready for review now.
