### ISSUE TITLE
Changing the soundtrack

### ISSUE THREAD

**Issue by MKerkhof** [thervh70/SEM_Team9#35]
- [x] The player can alter the soundtrack of the game.
  - [x] The player must be able to buy a new soundtrack in the shop if  the player has enough coins.
  - [x] The user must be able to change the soundtrack by clicking on a 'Set as current Soundtrack' button in the shop, just above the bottom of the scene.
  - [x]  The soundtrack in the Game must correspond to the soundtrack that is set to 'Current' in the shop.
  - [x] The user should be able to see what the current soundtrack is in the shop.
  - [x] The user should have an overview (a table or a list) in which it is clear which soundtracks are bought and which aren't and how expensive they are in the shop.
  - [ ] The user could click on a preview button, which, if is clicked on, an audioplayer is started which plays a short part of the soundtrack.

<feature

**Comment by thervh70** [comment]
This is a shop feature. The audio tracks will have to be defined in separate classes (just like all the skins) These classes will have a single super class.

This superclass also has a super class, ShopItem (or something like it) so we are able to fill a single table in the shopScene with all available shopitems.

**Comment by mdingjan** [comment]
I added  the requirements for this issue, please have a look!

<feature

**Comment by thervh70** [comment]
Closed in #182.
