### ISSUE TITLE
Power up items

### ISSUE THREAD

**Issue by MKerkhof** [thervh70/SEM_Team9#40]
Possible power-ups:
- [x] Invulnerability
- [ ] Slowness
- [ ] Coin magnet
- [ ] Super run (invul. and high speed)
- [ ] ...

**Comment by thervh70** [comment]
In my opinion this is an excellent feature for the 3rd iteration.
We can build this (as an extra feature) using the Decorator Pattern.

**Comment by mpsijm** [comment]
Requirements:
- The player shall be able to pick up power-ups.
  - When a power-up is picked up, the action belonging to the power-up  is executed immediately.
  - All actions will last for a yet to be determined time.
  - Some of the actions include: invulnerability, coins moving towards the Player, slowness.
