### ISSUE TITLE
More types of powerups

### ISSUE THREAD

**Issue by MKerkhof** [thervh70/SEM_Team9#41]
Obstacles can be destroyed with the shooting powerup. This also raises the score.

**Comment by thervh70** [comment]
Are we really going to implement it the way we described in the beginning?
I suppose we could make something like pacman, in which you are able to "eat" the objects when you are colliding (also making the dissappear or even explode) when you have a certain powerup.

< feature

**Comment by MathiasMeuleman** [comment]
In my opinion, we could make the following power ups work:
 - [ ] invincibility
 - [ ] destroyability 
 - [ ] slowness
Destroyability means, walking through an obstacle (let's say it's only possible for logs) destroys the obstacle and gives you points. Also, in the score overlay, the image (name should be gone)  of the powerup should be only visible when the powerup is active. The numbers indicating the duration should be replaced by a status bar. Any comments are welcome, again, this is just my opinion. 

<feature
