### ISSUE TITLE
Event Logger

### ISSUE THREAD

**Issue by mpsijm** [thervh70/SEM_Team9#68]
- The user shall be able to read a log file containing all events that have happened during the game.
  - The log shall have timestamps.
- Tasks for implementation:
  - [x] Make Game "observable"
  - [x] Make Logger class
  - [x] Make Logger observe Game
  - [x] Make Logger poop stuff to text file
    - [x] Button presses in Main Menu
    - [x] Game starts
    - [x] Player starts moving 
    - [x] Player stops moving
    - [x] Player jumps
    - [x] Player slides
    - [x] Player picks up coin
    - [x] Game is paused
    - [x] Game is continued
    - [x] Game is exited to Main Menu
    - [x] Player bumps into obstacle / Game ends
  - [x] Profit

**Comment by thervh70** [comment]
@mpsijm please check the checkboxes in the issue so we can easily see what you've done and how far you have progressed.

< review

**Comment by mpsijm** [comment]
Because a settings screen has been added, there are two new loggables:
- [ ] Settings button has been pressed
- [ ] Back button has been pressed in Main menu

**Comment by mdingjan** [comment]
Now that the last checkstyle warnings are fixed, this branch is ready to merged :)

<review
